repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
  - repo: https://github.com/concur1/sqruff-pre-commit
    # Sqruff version.
    rev: v0.38.0
    hooks:
      # Run the formatter.
      - id: sqruff-fix
        files: \.sql$
      # Run the linter.
      - id: sqruff-lint
        files: \.sql$

