-- noqa: disable=LT05
-- squawk-ignore-file prefer-bigint-over-smallint,changing-column-type,prefer-robust-stmts,require-concurrent-index-creation
-- noqa: enable=LT05

set statement_timeout = '5s' ;
set lock_timeout = '1s' ;
DROP MATERIALIZED VIEW IF EXISTS public.pet_year_avg CASCADE ;
DROP MATERIALIZED VIEW IF EXISTS public.pet_year_max CASCADE ;


CREATE TABLE IF NOT EXISTS public.locations (
id smallint PRIMARY KEY,
city text NOT NULL,
state text NOT NULL,
lat real NOT NULL,
lng real NOT NULL
) ;

DO $$
DECLARE
public_schema constant text := 'public' ;
pet_year_relation_kind "char" ;
BEGIN
SELECT
c.relkind
INTO pet_year_relation_kind
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE n.nspname = public_schema
AND c.relname = 'pet_year' ;

IF pet_year_relation_kind = 'm' THEN
EXECUTE format('DROP MATERIALIZED VIEW %I.pet_year CASCADE', public_schema) ;
ELSIF pet_year_relation_kind = 'v' THEN
EXECUTE format('DROP VIEW %I.pet_year CASCADE', public_schema) ;
END IF ;

IF EXISTS (
SELECT
1
FROM information_schema.columns
WHERE table_schema = public_schema
AND table_name = 'locations'
AND column_name = 'location_id'
)
AND NOT EXISTS (
SELECT
1
FROM information_schema.columns
WHERE table_schema = public_schema
AND table_name = 'locations'
AND column_name = 'id'
) THEN
ALTER TABLE public.locations RENAME COLUMN location_id TO id ;
END IF ;
END $$ ;

ALTER TABLE IF EXISTS public.locations
ALTER COLUMN id TYPE smallint USING id::smallint,
ALTER COLUMN lat TYPE real USING lat::real,
ALTER COLUMN lng TYPE real USING lng::real ;

CREATE TABLE IF NOT EXISTS public.pet (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
location_id smallint NOT NULL,
date date NOT NULL,
pet real NOT NULL
) ;

ALTER TABLE IF EXISTS public.pet
ALTER COLUMN id TYPE integer USING id::integer,
ALTER COLUMN location_id TYPE smallint USING location_id::smallint,
ALTER COLUMN pet TYPE real USING pet::real ;

DO $$
DECLARE
public_schema constant text := 'public' ;
BEGIN
IF EXISTS (
SELECT
1
FROM pg_catalog.pg_class AS i
JOIN pg_catalog.pg_index AS ix ON ix.indexrelid = i.oid
JOIN pg_catalog.pg_class AS t ON t.oid = ix.indrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid = i.relnamespace
WHERE n.nspname = public_schema
AND i.relname = 'id'
AND t.relname = 'pet'
) THEN
DROP INDEX public.id ;
END IF ;
END $$ ;

CREATE INDEX if not exists pet_location_date_covering_idx
ON public.pet (location_id, date)
INCLUDE (pet) ;

DO $$
DECLARE
public_schema constant text := 'public' ;
forecast_relation_kind "char" ;
BEGIN
SELECT
c.relkind
INTO forecast_relation_kind
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE n.nspname = public_schema
AND c.relname = 'pet_forecast' ;

IF forecast_relation_kind IN ('r', 'p') THEN
IF to_regclass('public.pet_forecast_legacy') IS NULL THEN
ALTER TABLE public.pet_forecast RENAME TO pet_forecast_legacy ;
ELSE
DROP TABLE public.pet_forecast CASCADE ;
END IF ;
END IF ;
END $$ ;
