"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod

"""Storage providers backends for Memory caching."""
CacheItemInfo = ...
class CacheWarning(Warning):
    """Warning to capture dump failures except for PicklingError."""
    ...


def concurrency_safe_write(object_to_write, filename, write_func): # -> str:
    """Writes an object into a unique file in a concurrency-safe way."""
    ...

class StoreBackendBase(metaclass=ABCMeta):
    """Helper Abstract Base Class which defines all methods that
    a StorageBackend must implement."""
    location = ...
    @abstractmethod
    def create_location(self, location): # -> None:
        """Creates a location on the store.

        Parameters
        ----------
        location: string
            The location in the store. On a filesystem, this corresponds to a
            directory.
        """
        ...
    
    @abstractmethod
    def clear_location(self, location): # -> None:
        """Clears a location on the store.

        Parameters
        ----------
        location: string
            The location in the store. On a filesystem, this corresponds to a
            directory or a filename absolute path
        """
        ...
    
    @abstractmethod
    def get_items(self): # -> None:
        """Returns the whole list of items available in the store.

        Returns
        -------
        The list of items identified by their ids (e.g filename in a
        filesystem).
        """
        ...
    
    @abstractmethod
    def configure(self, location, verbose=..., backend_options=...): # -> None:
        """Configures the store.

        Parameters
        ----------
        location: string
            The base location used by the store. On a filesystem, this
            corresponds to a directory.
        verbose: int
            The level of verbosity of the store
        backend_options: dict
            Contains a dictionary of named parameters used to configure the
            store backend.
        """
        ...
    


class StoreBackendMixin:
    """Class providing all logic for managing the store in a generic way.

    The StoreBackend subclass has to implement 3 methods: create_location,
    clear_location and configure. The StoreBackend also has to provide
    a private _open_item, _item_exists and _move_item methods. The _open_item
    method has to have the same signature as the builtin open and return a
    file-like object.
    """
    def load_item(self, call_id, verbose=..., timestamp=..., metadata=...): # -> Any:
        """Load an item from the store given its id as a list of str."""
        ...
    
    def dump_item(self, call_id, item, verbose=...): # -> None:
        """Dump an item in the store at the id given as a list of str."""
        ...
    
    def clear_item(self, call_id): # -> None:
        """Clear the item at the id, given as a list of str."""
        ...
    
    def contains_item(self, call_id):
        """Check if there is an item at the id, given as a list of str."""
        ...
    
    def get_item_info(self, call_id): # -> dict[str, Any]:
        """Return information about item."""
        ...
    
    def get_metadata(self, call_id): # -> Any | dict[Any, Any]:
        """Return actual metadata of an item."""
        ...
    
    def store_metadata(self, call_id, metadata): # -> None:
        """Store metadata of a computation."""
        ...
    
    def contains_path(self, call_id):
        """Check cached function is available in store."""
        ...
    
    def clear_path(self, call_id): # -> None:
        """Clear all items with a common path in the store."""
        ...
    
    def store_cached_func_code(self, call_id, func_code=...): # -> None:
        """Store the code of the cached function."""
        ...
    
    def get_cached_func_code(self, call_id):
        """Store the code of the cached function."""
        ...
    
    def get_cached_func_info(self, call_id): # -> dict[str, Any]:
        """Return information related to the cached function if it exists."""
        ...
    
    def clear(self): # -> None:
        """Clear the whole store content."""
        ...
    
    def enforce_store_limits(self, bytes_limit, items_limit=..., age_limit=...): # -> None:
        """
        Remove the store's oldest files to enforce item, byte, and age limits.
        """
        ...
    
    def __repr__(self): # -> str:
        """Printable representation of the store location."""
        ...
    


class FileSystemStoreBackend(StoreBackendBase, StoreBackendMixin):
    """A StoreBackend used with local or network file systems."""
    _open_item = ...
    _item_exists = ...
    _move_item = ...
    def clear_location(self, location): # -> None:
        """Delete location on store."""
        ...
    
    def create_location(self, location): # -> None:
        """Create object location on store"""
        ...
    
    def get_items(self): # -> list[Any]:
        """Returns the whole list of items available in the store."""
        ...
    
    def configure(self, location, verbose=..., backend_options=...): # -> None:
        """Configure the store backend.

        For this backend, valid store options are 'compress' and 'mmap_mode'
        """
        ...
    


